### ISSUE TITLE
Font change in 1.4.0? Or font shadow change?

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#12]
Did you changed the font shadow in 1.4.0? Text shadow looks slightly off the text (like 1-2pxl down)

**Comment by Nillx** [comment]
font:SetShadowOffset(1, -1) was the default

**Comment by cecilia-sanare** [comment]
Hmm, the shadow offset hasn't changed since the [original commit / 1.0.0 version](https://github.com/butter-cookie-kitkat/ButterQuestTracker/blame/master/ButterQuestTracker.lua#L339).

I'm fine with changing it to the default, I mostly changed it to (1, -2) to make the text stand out more in brighter zones.

Can you provide a screenshot of what it looks like for you? 
I'm running a 2k monitor so it may look less noticeable for me.

**Comment by Nillx** [comment]
https://imgur.com/a/5KhOrdz

Small difference but noticeable, especially if the background is bright. You can see the shadow detached from the text.

**Comment by cecilia-sanare** [comment]
Hey @Nillx this issue was just resolved in [v1.5.0](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2793986).

Let me know if you run into any other issues!

**Comment by Nillx** [comment]
Thanks for the quick updates, that works great.
