### ISSUE TITLE
Auto track the quest if you kill a quest monster/loot quest item.

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#20]
Got another tiny suggestion. 

Automatically start tracking the quest if you kill a mob (or any other quest progress). Think it worked like this on retail. You kill a quest NPC/Loot and it auto starts tracking the quest.

(hope im not spamming with too many requests!)

**Comment by cecilia-sanare** [comment]
Just want to verify, but is your use-case the following?

- User obtains a quest decides to untrack said quest making it no longer visible on the tracker.
- User then gets progress on said quest.

As a result the tracker should automatically remove the users override since they've gotten progress on the quest.

**Comment by Nillx** [comment]
Yes and display the quest

**Comment by cecilia-sanare** [comment]
Hey @Nillx this functionality is now available as of [1.7.0-rc.3](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2796083).

Let me know if you run into any issues!

**Comment by Nillx** [comment]
Thanks, ill check it now.

**Comment by Nillx** [comment]
Noticed a small bug. This seems to be working only on quests that are from my current zone. I had a quest taken from Undercity and marked as Undercity quest but the quest objective is in Arathi. Its not auto tracking the progress on that quest. Or this is affected by the current zone option?

**Comment by cecilia-sanare** [comment]
Hey @Nillx, correct this is impacted by the current zone option.

I'm basically just wiping out the manual tracking override for that specific quest so that filters can still impact it.

I'd be willing to add a toggle to make it forcibly track the quest upon being updated.

**Comment by Nillx** [comment]
Its fine, i toggled off Current zone quests

**Comment by Nillx** [comment]
Thanks for the quick development and for the willingness to add new features. After trying every possible quest tracking addon i can easily say that this one is the best of all right now. ThumbsUP

**Comment by cecilia-sanare** [comment]
I'm really glad to hear you like it! 
The current zone only functionality is what originally drove me to make this AddOn.

Just a heads up, I released [v1.7.0-rc.4](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2796206) which contains a bug fix and a toggle to automatically track quests when they're updated.

This should bypass any filters since they'll get tracked in the quest overrides.

**Comment by Nillx** [comment]
Thanks ill try it.
