### ISSUE TITLE
1.9.2 Frame settings broken

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#57]
Noticed that Position X Y in the frame settings are broken. Quest frame always goes in the top right corner, no matter what X Y numbers im using. You need to reload UI every time when you change the numbers.

**Comment by cecilia-sanare** [comment]
You're absolutely a 10/10!

Someone said that positioning the tracker was broken on CurseForge and for the life of me I couldn't reproduce it. It'd make sense that I couldn't reproduce it since I was moving it via the "Quests" header.

Seriously, thank you for taking the time to go into the details of how to reproduce the issue.
I really appreciate it.

**Comment by Nillx** [comment]
No problem :)
