### ISSUE TITLE
Broken embeds

### ISSUE THREAD

**Issue by Road-block** [butter-cookie-kitkat/ButterQuestTracker#94]
## Bug description
There's a multitude of problems with the embed references.
1. `<Include file="Libs\Poncho-1.0\Poncho-1.0.xml"/>` in embeds.xml is referencing a non-existent file.
2. Libs\Poncho-1.0 contains the Poncho-2.0 library.
3. Modules are trying to load the non-existent Poncho-1.0, for example 
`local CreateClass = LibStub("Poncho-1.0");`
in TrackerHelper\Modules\Base.lua

The only way this works is if another addon is loading Poncho-1.0 is my guess.

## Screenshots

**Butter Quest Tracker Version:** 1.9.20-classic

**Comment by Road-block** [comment]
So after fixing all the embeds references to point to [Poncho-2.0](https://github.com/Jaliborc/Poncho-2.0)  

Which means 

- Libs folder structure
- embeds.xml reference
- class instantiation for the 6 modules that use the library in TrackerHelper

The addon is still broken because Poncho-2.0 removes events that were available in Poncho-1.0 (:OnCreate, :OnAquire no longer available)

And considering the author, not only doesn't offer an upgrade path but doesn't even preserve the old major as a branch or in its own repo, I'd say you're simply getting screwed by the library.

**Comment by Road-block** [comment]
If you don't want to go through the trouble of rewriting the parts that use Poncho-1.0 to be compatible with Poncho-2.0, you'd probably have to update your submodules to point to the last commit of Poncho-1.0 (assuming Libs are pulled in this way and not with some packager script)

**Comment by cecilia-sanare** [comment]
Hey @Road-block thanks for the heads up regarding this issue.

I've locked down the Poncho library to 1.0.1 which will alleviate the issue for now.
I'm not planning on updating to 2.0, mostly because BQT is going through a rewrite of it's GUI anyways.

This issue should now be resolved in [1.9.21](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2844207).
Let me know if you run into any other issues!
